<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <!--
    File: channels.xsl
    Created by: Viktor Zetterstöm (vize1500)
    Course: DT074G, Mittuniversitetet

    This file combines the three channels, svt1, svt2 and kunskapskanalen into
    one xml-file. This is done using for-each loops and copy-of. The path to the
    respective logo for each channel is also added in this new XML-file.
    -->


    <!-- Set output to xml -->
    <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>


    <!-- Variables -->
    <!-- Channel and logo paths -->
    <xsl:variable name="svt1">channels/svt1.svt.se_2018-10-15.xml</xsl:variable>
    <xsl:variable name="svt2">channels/svt2.svt.se_2018-10-15.xml</xsl:variable>
    <xsl:variable name="kunskapskanalen">channels/kunskapskanalen.svt.se_2018-10-15.xml</xsl:variable>
    <xsl:variable name="svt1-logo">logos/svt1.svt.se.png</xsl:variable>
    <xsl:variable name="svt2-logo">logos/svt2.svt.se.png</xsl:variable>
    <xsl:variable name="kunskapskanalen-logo">logos/kunskapskanalen.svt.se.png</xsl:variable>

    <!-- TV-guide name and creator variable -->
    <xsl:variable name="tv-guide-title">The vize1500 TV-guide</xsl:variable>
    <xsl:variable name="tv-guide-creator">Viktor Zetterström</xsl:variable>


    <!-- Main template -->
    <xsl:template match="/">
        <xsl:comment>This is an file generated by the .xsl file channels.xsl, and is a combination of the channels included in the channels subfolder.</xsl:comment>
        <tv-guide>

            <!-- General tv-guide info -->
            <tv-guide-title><xsl:value-of select="$tv-guide-title" /></tv-guide-title>
            <tv-guide-creator><xsl:value-of select="$tv-guide-creator"/></tv-guide-creator>


            <!-- All program data is copied from channels -->
            <!-- Logo and channel names are added -->
            <!-- SVT 1 -->
            <channel>
                <channel-name>svt1</channel-name>
                <logo-path><xsl:value-of select="$svt1-logo" /></logo-path>
                <xsl:apply-templates select="document($svt1)/tv" />
            </channel>

            <!-- SVT2 -->
            <channel>
                <channel-name>svt2</channel-name>
                <logo-path><xsl:value-of select="$svt1-logo" /></logo-path>
                <xsl:apply-templates select="document($svt2)/tv" />
            </channel>

            <!-- Kunskapskanalen -->
            <channel>
                <channel-name>kunskapskanalen</channel-name>
                <logo-path><xsl:value-of select="$svt1-logo" /></logo-path>
                <xsl:apply-templates select="document($kunskapskanalen)/tv" />
            </channel>


        </tv-guide>
    </xsl:template>

    <!-- Template for copying channel data -->
    <xsl:template match="tv">
        <!-- Copy all programmes -->
        <xsl:for-each select="//programme">
            <xsl:copy-of select="." />
        </xsl:for-each>
    </xsl:template>


</xsl:stylesheet>